# Generated by Django 5.1.4 on 2025-06-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('num_alumnos', models.PositiveIntegerField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='localizacion.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=150)),
                ('num_control', models.CharField(max_length=20)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='localizacion.escuela')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='localizacion.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='localizacion.estado')),
            ],
        ),
        migrations.AddField(
            model_name='escuela',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='localizacion.municipio'),
        ),
    ]
