# Generated by Django 5.1.4 on 2025-06-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntornoVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_vr', to='test.dimension')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_vr', to='localizacion.escuela')),
                ('riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_vr', to='test.riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientadores', to='localizacion.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_frec', models.CharField(max_length=100)),
                ('activa', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_frecuentes', to='test.dimension')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='localizacion.escuela')),
                ('riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_frecuentes', to='test.riesgo')),
                ('respuesta_frec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='orientador.respuestafrecuente')),
            ],
        ),
    ]
