# Generated by Django 5.1.4 on 2025-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
