# Generated by Django 5.1.4 on 2025-06-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0002_alter_preguntafrecuente_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='entornovr',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entornovr',
            name='nombre',
            field=models.CharField(blank=True, default='Video de apoyo', max_length=120, null=True),
        ),
    ]
