# Generated by Django 5.1.4 on 2025-06-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0003_entornovr_descripcion_entornovr_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientadorToken',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('orientador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='orientador.orientador')),
            ],
        ),
    ]
