# Generated by Django 5.1.4 on 2025-06-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(max_length=50)),
                ('min_val', models.IntegerField()),
                ('max_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='test.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='test.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='test.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='localizacion.alumno')),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='test.dimension')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='test.evaluacion')),
                ('riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='test.riesgo')),
            ],
        ),
    ]
