# Generated by Django 5.1.4 on 2025-06-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
